// Copyright (c) 2005-2016 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD/e, an XML Schema
// to C++ data binding compiler for embedded systems.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

#ifndef PHENOTYPE_SSKEL_HPP
#define PHENOTYPE_SSKEL_HPP

#include <xsde/cxx/version.hxx>

#if (XSDE_INT_VERSION != 3020000L)
#error XSD/e runtime version mismatch
#endif

#include <xsde/cxx/config.hxx>

#ifndef XSDE_ENCODING_UTF8
#error the generated code uses the UTF-8 encodingwhile the XSD/e runtime does not (reconfigure the runtime or change the --char-encoding value)
#endif

#ifndef XSDE_STL
#error the generated code uses STL while the XSD/e runtime does not (reconfigure the runtime or add --no-stl)
#endif

#ifndef XSDE_IOSTREAM
#error the generated code uses iostream while the XSD/e runtime does not (reconfigure the runtime or add --no-iostream)
#endif

#ifndef XSDE_EXCEPTIONS
#error the generated code uses exceptions while the XSD/e runtime does not (reconfigure the runtime or add --no-exceptions)
#endif

#ifndef XSDE_LONGLONG
#error the generated code uses long long while the XSD/e runtime does not (reconfigure the runtime or add --no-long-long)
#endif

#ifdef XSDE_SERIALIZER_VALIDATION
#error the XSD/e runtime uses validation while the generated code does not (reconfigure the runtime or remove --suppress-validation)
#endif

#ifndef XSDE_POLYMORPHIC
#error the generated code expects XSD/e runtime with polymorphism support (reconfigure the runtime or remove --generate-polymorphic/--runtime-polymorphic)
#endif

#ifndef XSDE_REUSE_STYLE_TIEIN
#error the generated code uses the tiein reuse style while the XSD/e runtime does not (reconfigure the runtime or add --reuse-style-mixin or --reuse-style-none)
#endif

#ifdef XSDE_CUSTOM_ALLOCATOR
#error the XSD/e runtime uses custom allocator while the generated code does not (reconfigure the runtime or add --custom-allocator)
#endif

#include <xsde/cxx/pre.hxx>

// Begin prologue.
//

#include <xsde/cxx/hybrid/any-type.hxx>
#include <xsde/cxx/hybrid/any-type-sskel.hxx>
#include <xsde/cxx/hybrid/any-type-simpl.hxx>

namespace xml_schema
{
  using ::xsde::cxx::hybrid::any_type;

  using ::xsde::cxx::hybrid::any_type_sskel;
  using ::xsde::cxx::hybrid::any_type_simpl;
}


//
// End prologue.

// Forward declarations
//
namespace phenotype
{
  class phenotype_elements_sskel;
  class phenotype_sskel;
}


#include <string>

#include <xsde/cxx/serializer/xml-schema.hxx>

#include <xsde/cxx/serializer/exceptions.hxx>

#include <xsde/cxx/serializer/map.hxx>
#include <xsde/cxx/serializer/substitution-map-callback.hxx>
#include <xsde/cxx/serializer/substitution-map-load.hxx>

#include <xsde/cxx/serializer/non-validating/serializer.hxx>
#include <xsde/cxx/serializer/non-validating/xml-schema-sskel.hxx>
#include <xsde/cxx/serializer/non-validating/xml-schema-simpl.hxx>

#include <xsde/cxx/serializer/genx/document.hxx>

#include "phenotype.hpp"

namespace xml_schema
{
  // Built-in XML Schema types mapping.
  //
  using ::xsde::cxx::string_sequence;
  using ::xsde::cxx::qname;
  using ::xsde::cxx::buffer;
  using ::xsde::cxx::time_zone;
  using ::xsde::cxx::gday;
  using ::xsde::cxx::gmonth;
  using ::xsde::cxx::gyear;
  using ::xsde::cxx::gmonth_day;
  using ::xsde::cxx::gyear_month;
  using ::xsde::cxx::date;
  using ::xsde::cxx::time;
  using ::xsde::cxx::date_time;
  using ::xsde::cxx::duration;

  // Base serializer skeletons.
  //
  using ::xsde::cxx::serializer::serializer_base;
  typedef ::xsde::cxx::serializer::non_validating::empty_content serializer_empty_content;
  typedef ::xsde::cxx::serializer::non_validating::simple_content serializer_simple_content;
  typedef ::xsde::cxx::serializer::non_validating::complex_content serializer_complex_content;

  // Serializer map interface and default implementation.
  //
  using ::xsde::cxx::serializer::serializer_map;
  using ::xsde::cxx::serializer::serializer_map_impl;

  // Serializer substitution map callack.
  //
  using ::xsde::cxx::serializer::serializer_smap_callback;

  // Substitution and inheritance hashmaps load querying.
  //
  using ::xsde::cxx::serializer::serializer_smap_buckets;
  using ::xsde::cxx::serializer::serializer_smap_elements;
  using ::xsde::cxx::serializer::serializer_smap_bucket_buckets;
  using ::xsde::cxx::serializer::serializer_smap_bucket_elements;

  // Serializer skeletons and implementations for the
  // XML Schema built-in types.
  //
  using ::xsde::cxx::serializer::non_validating::any_simple_type_sskel;
  using ::xsde::cxx::serializer::non_validating::any_simple_type_simpl;

  using ::xsde::cxx::serializer::non_validating::byte_sskel;
  using ::xsde::cxx::serializer::non_validating::byte_simpl;

  using ::xsde::cxx::serializer::non_validating::unsigned_byte_sskel;
  using ::xsde::cxx::serializer::non_validating::unsigned_byte_simpl;

  using ::xsde::cxx::serializer::non_validating::short_sskel;
  using ::xsde::cxx::serializer::non_validating::short_simpl;

  using ::xsde::cxx::serializer::non_validating::unsigned_short_sskel;
  using ::xsde::cxx::serializer::non_validating::unsigned_short_simpl;

  using ::xsde::cxx::serializer::non_validating::int_sskel;
  using ::xsde::cxx::serializer::non_validating::int_simpl;

  using ::xsde::cxx::serializer::non_validating::unsigned_int_sskel;
  using ::xsde::cxx::serializer::non_validating::unsigned_int_simpl;

  using ::xsde::cxx::serializer::non_validating::long_sskel;
  using ::xsde::cxx::serializer::non_validating::long_simpl;

  using ::xsde::cxx::serializer::non_validating::unsigned_long_sskel;
  using ::xsde::cxx::serializer::non_validating::unsigned_long_simpl;

  using ::xsde::cxx::serializer::non_validating::integer_sskel;
  using ::xsde::cxx::serializer::non_validating::integer_simpl;

  using ::xsde::cxx::serializer::non_validating::non_positive_integer_sskel;
  using ::xsde::cxx::serializer::non_validating::non_positive_integer_simpl;

  using ::xsde::cxx::serializer::non_validating::non_negative_integer_sskel;
  using ::xsde::cxx::serializer::non_validating::non_negative_integer_simpl;

  using ::xsde::cxx::serializer::non_validating::positive_integer_sskel;
  using ::xsde::cxx::serializer::non_validating::positive_integer_simpl;

  using ::xsde::cxx::serializer::non_validating::negative_integer_sskel;
  using ::xsde::cxx::serializer::non_validating::negative_integer_simpl;

  using ::xsde::cxx::serializer::non_validating::boolean_sskel;
  using ::xsde::cxx::serializer::non_validating::boolean_simpl;

  using ::xsde::cxx::serializer::non_validating::float_sskel;
  using ::xsde::cxx::serializer::non_validating::float_simpl;

  using ::xsde::cxx::serializer::non_validating::double_sskel;
  using ::xsde::cxx::serializer::non_validating::double_simpl;

  using ::xsde::cxx::serializer::non_validating::decimal_sskel;
  using ::xsde::cxx::serializer::non_validating::decimal_simpl;

  using ::xsde::cxx::serializer::non_validating::string_sskel;
  using ::xsde::cxx::serializer::non_validating::string_simpl;

  using ::xsde::cxx::serializer::non_validating::normalized_string_sskel;
  using ::xsde::cxx::serializer::non_validating::normalized_string_simpl;

  using ::xsde::cxx::serializer::non_validating::token_sskel;
  using ::xsde::cxx::serializer::non_validating::token_simpl;

  using ::xsde::cxx::serializer::non_validating::name_sskel;
  using ::xsde::cxx::serializer::non_validating::name_simpl;

  using ::xsde::cxx::serializer::non_validating::nmtoken_sskel;
  using ::xsde::cxx::serializer::non_validating::nmtoken_simpl;

  using ::xsde::cxx::serializer::non_validating::nmtokens_sskel;
  using ::xsde::cxx::serializer::non_validating::nmtokens_simpl;

  using ::xsde::cxx::serializer::non_validating::ncname_sskel;
  using ::xsde::cxx::serializer::non_validating::ncname_simpl;

  using ::xsde::cxx::serializer::non_validating::language_sskel;
  using ::xsde::cxx::serializer::non_validating::language_simpl;

  using ::xsde::cxx::serializer::non_validating::id_sskel;
  using ::xsde::cxx::serializer::non_validating::id_simpl;

  using ::xsde::cxx::serializer::non_validating::idref_sskel;
  using ::xsde::cxx::serializer::non_validating::idref_simpl;

  using ::xsde::cxx::serializer::non_validating::idrefs_sskel;
  using ::xsde::cxx::serializer::non_validating::idrefs_simpl;

  using ::xsde::cxx::serializer::non_validating::uri_sskel;
  using ::xsde::cxx::serializer::non_validating::uri_simpl;

  using ::xsde::cxx::serializer::non_validating::qname_sskel;
  using ::xsde::cxx::serializer::non_validating::qname_simpl;

  using ::xsde::cxx::serializer::non_validating::base64_binary_sskel;
  using ::xsde::cxx::serializer::non_validating::base64_binary_simpl;

  using ::xsde::cxx::serializer::non_validating::hex_binary_sskel;
  using ::xsde::cxx::serializer::non_validating::hex_binary_simpl;

  using ::xsde::cxx::serializer::non_validating::date_sskel;
  using ::xsde::cxx::serializer::non_validating::date_simpl;

  using ::xsde::cxx::serializer::non_validating::date_time_sskel;
  using ::xsde::cxx::serializer::non_validating::date_time_simpl;

  using ::xsde::cxx::serializer::non_validating::duration_sskel;
  using ::xsde::cxx::serializer::non_validating::duration_simpl;

  using ::xsde::cxx::serializer::non_validating::gday_sskel;
  using ::xsde::cxx::serializer::non_validating::gday_simpl;

  using ::xsde::cxx::serializer::non_validating::gmonth_sskel;
  using ::xsde::cxx::serializer::non_validating::gmonth_simpl;

  using ::xsde::cxx::serializer::non_validating::gmonth_day_sskel;
  using ::xsde::cxx::serializer::non_validating::gmonth_day_simpl;

  using ::xsde::cxx::serializer::non_validating::gyear_sskel;
  using ::xsde::cxx::serializer::non_validating::gyear_simpl;

  using ::xsde::cxx::serializer::non_validating::gyear_month_sskel;
  using ::xsde::cxx::serializer::non_validating::gyear_month_simpl;

  using ::xsde::cxx::serializer::non_validating::time_sskel;
  using ::xsde::cxx::serializer::non_validating::time_simpl;

  // Error codes.
  //
  typedef xsde::cxx::serializer::genx::xml_error serializer_xml_error;

  // Exceptions.
  //
  typedef xsde::cxx::serializer::exception serializer_exception;
  typedef xsde::cxx::serializer::xml serializer_xml;

  // Document serializer.
  //
  using xsde::cxx::serializer::genx::writer;
  using xsde::cxx::serializer::genx::document_simpl;

  // Serializer context.
  //
  typedef xsde::cxx::serializer::context serializer_context;
}

#include "common-sskel.hpp"

#include "cell_cycle-sskel.hpp"

#include "phenotype_base-sskel.hpp"

namespace phenotype
{
  class phenotype_elements_sskel: public ::cell_cycle::cycles_and_deaths_sskel
  {
    public:
    // Serializer callbacks. Override them in your implementation.
    //

    virtual void
    pre (const ::phenotype::phenotype_elements&) = 0;

    // Elements.
    //
    virtual bool
    adhesion_present ();

    virtual const ::phenotype_common::adhesion&
    adhesion () = 0;

    virtual bool
    geometrical_properties_present ();

    virtual const ::phenotype_common::geometrical_properties&
    geometrical_properties () = 0;

    virtual bool
    mass_present ();

    virtual const ::phenotype_common::mass&
    mass () = 0;

    virtual bool
    mechanics_present ();

    virtual const ::phenotype_common::mechanics&
    mechanics () = 0;

    virtual bool
    motility_present ();

    virtual const ::phenotype_common::motility&
    motility () = 0;

    virtual bool
    PKPD_present ();

    virtual const ::pkpd::PKPD&
    PKPD () = 0;

    virtual bool
    timescale_present ();

    virtual const ::phenotype_base::expected_timescale&
    timescale () = 0;

    virtual bool
    transport_processes_present ();

    virtual const ::phenotype_common::transport_processes&
    transport_processes () = 0;

    virtual bool
    custom_present ();

    virtual const ::common::custom&
    custom () = 0;

    // virtual void
    // post ();

    // Serializer construction API.
    //
    void
    serializers (::cell_cycle::cell_cycle_sskel& /* cell_cycle */,
                 ::cell_cycle::cell_death_sskel& /* cell_death */,
                 ::phenotype_common::adhesion_sskel& /* adhesion */,
                 ::phenotype_common::geometrical_properties_sskel& /* geometrical_properties */,
                 ::phenotype_common::mass_sskel& /* mass */,
                 ::phenotype_common::mechanics_sskel& /* mechanics */,
                 ::phenotype_common::motility_sskel& /* motility */,
                 ::pkpd::PKPD_sskel& /* PKPD */,
                 ::phenotype_base::expected_timescale_sskel& /* timescale */,
                 ::phenotype_common::transport_processes_sskel& /* transport_processes */,
                 ::common::custom_sskel& /* custom */);

    void
    serializer_maps (::xml_schema::serializer_map& /* cell_cycle */,
                     ::xml_schema::serializer_map& /* cell_death */,
                     ::xml_schema::serializer_map& /* adhesion */,
                     ::xml_schema::serializer_map& /* geometrical_properties */,
                     ::xml_schema::serializer_map& /* mass */,
                     ::xml_schema::serializer_map& /* mechanics */,
                     ::xml_schema::serializer_map& /* motility */,
                     ::xml_schema::serializer_map& /* PKPD */,
                     ::xml_schema::serializer_map& /* timescale */,
                     ::xml_schema::serializer_map& /* transport_processes */,
                     ::xml_schema::serializer_map& /* custom */);

    // Individual element serializers.
    //
    void
    adhesion_serializer (::phenotype_common::adhesion_sskel&);

    void
    adhesion_serializer (::xml_schema::serializer_map&);

    void
    geometrical_properties_serializer (::phenotype_common::geometrical_properties_sskel&);

    void
    geometrical_properties_serializer (::xml_schema::serializer_map&);

    void
    mass_serializer (::phenotype_common::mass_sskel&);

    void
    mass_serializer (::xml_schema::serializer_map&);

    void
    mechanics_serializer (::phenotype_common::mechanics_sskel&);

    void
    mechanics_serializer (::xml_schema::serializer_map&);

    void
    motility_serializer (::phenotype_common::motility_sskel&);

    void
    motility_serializer (::xml_schema::serializer_map&);

    void
    PKPD_serializer (::pkpd::PKPD_sskel&);

    void
    PKPD_serializer (::xml_schema::serializer_map&);

    void
    timescale_serializer (::phenotype_base::expected_timescale_sskel&);

    void
    timescale_serializer (::xml_schema::serializer_map&);

    void
    transport_processes_serializer (::phenotype_common::transport_processes_sskel&);

    void
    transport_processes_serializer (::xml_schema::serializer_map&);

    void
    custom_serializer (::common::custom_sskel&);

    void
    custom_serializer (::xml_schema::serializer_map&);

    virtual void
    _reset ();

    // Constructor.
    //
    phenotype_elements_sskel (::cell_cycle::cycles_and_deaths_sskel* tiein);

    public:
    static const char*
    _static_type ();

    virtual const char*
    _dynamic_type () const;

    // Implementation.
    //
    public:
    virtual void
    pre (const ::cell_cycle::cycles_and_deaths&);

    virtual const ::cell_cycle::cell_cycle&
    cell_cycle ();

    virtual const ::cell_cycle::cell_death&
    cell_death ();

    virtual void
    _serialize_content ();

    protected:
    phenotype_elements_sskel* phenotype_elements_impl_;
    phenotype_elements_sskel (phenotype_elements_sskel*, void*);

    protected:
    ::phenotype_common::adhesion_sskel* adhesion_serializer_;
    ::xml_schema::serializer_map* adhesion_serializer_map_;

    ::phenotype_common::geometrical_properties_sskel* geometrical_properties_serializer_;
    ::xml_schema::serializer_map* geometrical_properties_serializer_map_;

    ::phenotype_common::mass_sskel* mass_serializer_;
    ::xml_schema::serializer_map* mass_serializer_map_;

    ::phenotype_common::mechanics_sskel* mechanics_serializer_;
    ::xml_schema::serializer_map* mechanics_serializer_map_;

    ::phenotype_common::motility_sskel* motility_serializer_;
    ::xml_schema::serializer_map* motility_serializer_map_;

    ::pkpd::PKPD_sskel* PKPD_serializer_;
    ::xml_schema::serializer_map* PKPD_serializer_map_;

    ::phenotype_base::expected_timescale_sskel* timescale_serializer_;
    ::xml_schema::serializer_map* timescale_serializer_map_;

    ::phenotype_common::transport_processes_sskel* transport_processes_serializer_;
    ::xml_schema::serializer_map* transport_processes_serializer_map_;

    ::common::custom_sskel* custom_serializer_;
    ::xml_schema::serializer_map* custom_serializer_map_;
  };

  class phenotype_sskel: public ::phenotype::phenotype_elements_sskel
  {
    public:
    // Serializer callbacks. Override them in your implementation.
    //

    virtual void
    pre (const ::phenotype::phenotype&) = 0;

    // Attributes.
    //
    virtual bool
    type_present ();

    virtual const ::phenotype_base::phenotype_type&
    type () = 0;

    // virtual void
    // post ();

    // Serializer construction API.
    //
    void
    serializers (::cell_cycle::cell_cycle_sskel& /* cell_cycle */,
                 ::cell_cycle::cell_death_sskel& /* cell_death */,
                 ::phenotype_common::adhesion_sskel& /* adhesion */,
                 ::phenotype_common::geometrical_properties_sskel& /* geometrical_properties */,
                 ::phenotype_common::mass_sskel& /* mass */,
                 ::phenotype_common::mechanics_sskel& /* mechanics */,
                 ::phenotype_common::motility_sskel& /* motility */,
                 ::pkpd::PKPD_sskel& /* PKPD */,
                 ::phenotype_base::expected_timescale_sskel& /* timescale */,
                 ::phenotype_common::transport_processes_sskel& /* transport_processes */,
                 ::common::custom_sskel& /* custom */,
                 ::phenotype_base::phenotype_type_sskel& /* type */);

    // Individual attribute serializers.
    //
    void
    type_serializer (::phenotype_base::phenotype_type_sskel&);

    virtual void
    _reset ();

    // Constructor.
    //
    phenotype_sskel (::phenotype::phenotype_elements_sskel* tiein);

    public:
    static const char*
    _static_type ();

    virtual const char*
    _dynamic_type () const;

    // Implementation.
    //
    public:
    virtual void
    pre (const ::phenotype::phenotype_elements&);

    virtual const ::phenotype_common::adhesion&
    adhesion ();

    virtual const ::phenotype_common::geometrical_properties&
    geometrical_properties ();

    virtual const ::phenotype_common::mass&
    mass ();

    virtual const ::phenotype_common::mechanics&
    mechanics ();

    virtual const ::phenotype_common::motility&
    motility ();

    virtual const ::pkpd::PKPD&
    PKPD ();

    virtual const ::phenotype_base::expected_timescale&
    timescale ();

    virtual const ::phenotype_common::transport_processes&
    transport_processes ();

    virtual const ::common::custom&
    custom ();

    virtual void
    _serialize_attributes ();

    protected:
    phenotype_sskel* phenotype_impl_;
    phenotype_sskel (phenotype_sskel*, void*);

    protected:
    ::phenotype_base::phenotype_type_sskel* type_serializer_;
  };
}

#include "phenotype-sskel.ipp"

// Begin epilogue.
//
//
// End epilogue.

#include <xsde/cxx/post.hxx>

#endif // PHENOTYPE_SSKEL_HPP
