// Copyright (c) 2005-2016 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD/e, an XML Schema
// to C++ data binding compiler for embedded systems.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

#ifndef STATE_PSKEL_HPP
#define STATE_PSKEL_HPP

#include <xsde/cxx/version.hxx>

#if (XSDE_INT_VERSION != 3020000L)
#error XSD/e runtime version mismatch
#endif

#include <xsde/cxx/config.hxx>

#ifndef XSDE_ENCODING_UTF8
#error the generated code uses the UTF-8 encodingwhile the XSD/e runtime does not (reconfigure the runtime or change the --char-encoding value)
#endif

#ifndef XSDE_STL
#error the generated code uses STL while the XSD/e runtime does not (reconfigure the runtime or add --no-stl)
#endif

#ifndef XSDE_IOSTREAM
#error the generated code uses iostream while the XSD/e runtime does not (reconfigure the runtime or add --no-iostream)
#endif

#ifndef XSDE_EXCEPTIONS
#error the generated code uses exceptions while the XSD/e runtime does not (reconfigure the runtime or add --no-exceptions)
#endif

#ifndef XSDE_LONGLONG
#error the generated code uses long long while the XSD/e runtime does not (reconfigure the runtime or add --no-long-long)
#endif

#ifndef XSDE_PARSER_VALIDATION
#error the generated code uses validation while the XSD/e runtime does not (reconfigure the runtime or add --suppress-validation)
#endif

#ifndef XSDE_POLYMORPHIC
#error the generated code expects XSD/e runtime with polymorphism support (reconfigure the runtime or remove --generate-polymorphic/--runtime-polymorphic)
#endif

#ifndef XSDE_REUSE_STYLE_TIEIN
#error the generated code uses the tiein reuse style while the XSD/e runtime does not (reconfigure the runtime or add --reuse-style-mixin or --reuse-style-none)
#endif

#ifdef XSDE_CUSTOM_ALLOCATOR
#error the XSD/e runtime uses custom allocator while the generated code does not (reconfigure the runtime or add --custom-allocator)
#endif

#include <xsde/cxx/pre.hxx>

// Begin prologue.
//

#include <xsde/cxx/hybrid/any-type.hxx>
#include <xsde/cxx/hybrid/any-type-pskel.hxx>
#include <xsde/cxx/hybrid/any-type-pimpl.hxx>

namespace xml_schema
{
  using ::xsde::cxx::hybrid::any_type;

  using ::xsde::cxx::hybrid::any_type_pskel;
  using ::xsde::cxx::hybrid::any_type_pimpl;
}


//
// End prologue.

// Forward declarations
//
namespace state
{
  class phase_name_pskel;
  class phase_pskel;
  class orientation_formalism_pskel;
  class orientation_pskel;
  class cell_parts_pskel;
  class state_pskel;
  class adhered_cell_pskel;
  class list_of_adhered_cells_pskel;
}


#include <xsde/cxx/ro-string.hxx>

#include <xsde/cxx/parser/xml-schema.hxx>

#include <xsde/cxx/parser/exceptions.hxx>

#include <xsde/cxx/parser/map.hxx>
#include <xsde/cxx/parser/substitution-map-callback.hxx>
#include <xsde/cxx/parser/substitution-map-load.hxx>
#include <xsde/cxx/parser/validating/inheritance-map-load.hxx>

#include <xsde/cxx/stack.hxx>
#include <xsde/cxx/parser/validating/parser.hxx>
#include <xsde/cxx/parser/validating/xml-schema-pskel.hxx>
#include <xsde/cxx/parser/validating/xml-schema-pimpl.hxx>

#include <xsde/cxx/parser/expat/document.hxx>

#include "state.hpp"

namespace xml_schema
{
  // Built-in XML Schema types mapping.
  //
  using ::xsde::cxx::string_sequence;
  using ::xsde::cxx::qname;
  using ::xsde::cxx::buffer;
  using ::xsde::cxx::time_zone;
  using ::xsde::cxx::gday;
  using ::xsde::cxx::gmonth;
  using ::xsde::cxx::gyear;
  using ::xsde::cxx::gmonth_day;
  using ::xsde::cxx::gyear_month;
  using ::xsde::cxx::date;
  using ::xsde::cxx::time;
  using ::xsde::cxx::date_time;
  using ::xsde::cxx::duration;

  // Base parser skeletons.
  //
  using ::xsde::cxx::parser::parser_base;
  typedef ::xsde::cxx::parser::validating::empty_content parser_empty_content;
  typedef ::xsde::cxx::parser::validating::simple_content parser_simple_content;
  typedef ::xsde::cxx::parser::validating::complex_content parser_complex_content;
  typedef ::xsde::cxx::parser::validating::list_base parser_list_base;

  // Parser map interface and default implementation.
  //
  using ::xsde::cxx::parser::parser_map;
  using ::xsde::cxx::parser::parser_map_impl;

  // Parser substitution map callack.
  //
  using ::xsde::cxx::parser::parser_smap_callback;

  // Substitution and inheritance hashmaps load querying.
  //
  using ::xsde::cxx::parser::parser_smap_buckets;
  using ::xsde::cxx::parser::parser_smap_elements;
  using ::xsde::cxx::parser::validating::parser_imap_buckets;
  using ::xsde::cxx::parser::validating::parser_imap_elements;

  // Parser skeletons and implementations for the XML Schema
  // built-in types.
  //
  using ::xsde::cxx::parser::validating::any_simple_type_pskel;
  using ::xsde::cxx::parser::validating::any_simple_type_pimpl;

  using ::xsde::cxx::parser::validating::byte_pskel;
  using ::xsde::cxx::parser::validating::byte_pimpl;

  using ::xsde::cxx::parser::validating::unsigned_byte_pskel;
  using ::xsde::cxx::parser::validating::unsigned_byte_pimpl;

  using ::xsde::cxx::parser::validating::short_pskel;
  using ::xsde::cxx::parser::validating::short_pimpl;

  using ::xsde::cxx::parser::validating::unsigned_short_pskel;
  using ::xsde::cxx::parser::validating::unsigned_short_pimpl;

  using ::xsde::cxx::parser::validating::int_pskel;
  using ::xsde::cxx::parser::validating::int_pimpl;

  using ::xsde::cxx::parser::validating::unsigned_int_pskel;
  using ::xsde::cxx::parser::validating::unsigned_int_pimpl;

  using ::xsde::cxx::parser::validating::long_pskel;
  using ::xsde::cxx::parser::validating::long_pimpl;

  using ::xsde::cxx::parser::validating::unsigned_long_pskel;
  using ::xsde::cxx::parser::validating::unsigned_long_pimpl;

  using ::xsde::cxx::parser::validating::integer_pskel;
  using ::xsde::cxx::parser::validating::integer_pimpl;

  using ::xsde::cxx::parser::validating::non_positive_integer_pskel;
  using ::xsde::cxx::parser::validating::non_positive_integer_pimpl;

  using ::xsde::cxx::parser::validating::non_negative_integer_pskel;
  using ::xsde::cxx::parser::validating::non_negative_integer_pimpl;

  using ::xsde::cxx::parser::validating::positive_integer_pskel;
  using ::xsde::cxx::parser::validating::positive_integer_pimpl;

  using ::xsde::cxx::parser::validating::negative_integer_pskel;
  using ::xsde::cxx::parser::validating::negative_integer_pimpl;

  using ::xsde::cxx::parser::validating::boolean_pskel;
  using ::xsde::cxx::parser::validating::boolean_pimpl;

  using ::xsde::cxx::parser::validating::float_pskel;
  using ::xsde::cxx::parser::validating::float_pimpl;

  using ::xsde::cxx::parser::validating::double_pskel;
  using ::xsde::cxx::parser::validating::double_pimpl;

  using ::xsde::cxx::parser::validating::decimal_pskel;
  using ::xsde::cxx::parser::validating::decimal_pimpl;

  using ::xsde::cxx::parser::validating::string_pskel;
  using ::xsde::cxx::parser::validating::string_pimpl;

  using ::xsde::cxx::parser::validating::normalized_string_pskel;
  using ::xsde::cxx::parser::validating::normalized_string_pimpl;

  using ::xsde::cxx::parser::validating::token_pskel;
  using ::xsde::cxx::parser::validating::token_pimpl;

  using ::xsde::cxx::parser::validating::name_pskel;
  using ::xsde::cxx::parser::validating::name_pimpl;

  using ::xsde::cxx::parser::validating::nmtoken_pskel;
  using ::xsde::cxx::parser::validating::nmtoken_pimpl;

  using ::xsde::cxx::parser::validating::nmtokens_pskel;
  using ::xsde::cxx::parser::validating::nmtokens_pimpl;

  using ::xsde::cxx::parser::validating::ncname_pskel;
  using ::xsde::cxx::parser::validating::ncname_pimpl;

  using ::xsde::cxx::parser::validating::language_pskel;
  using ::xsde::cxx::parser::validating::language_pimpl;

  using ::xsde::cxx::parser::validating::id_pskel;
  using ::xsde::cxx::parser::validating::id_pimpl;

  using ::xsde::cxx::parser::validating::idref_pskel;
  using ::xsde::cxx::parser::validating::idref_pimpl;

  using ::xsde::cxx::parser::validating::idrefs_pskel;
  using ::xsde::cxx::parser::validating::idrefs_pimpl;

  using ::xsde::cxx::parser::validating::uri_pskel;
  using ::xsde::cxx::parser::validating::uri_pimpl;

  using ::xsde::cxx::parser::validating::qname_pskel;
  using ::xsde::cxx::parser::validating::qname_pimpl;

  using ::xsde::cxx::parser::validating::base64_binary_pskel;
  using ::xsde::cxx::parser::validating::base64_binary_pimpl;

  using ::xsde::cxx::parser::validating::hex_binary_pskel;
  using ::xsde::cxx::parser::validating::hex_binary_pimpl;

  using ::xsde::cxx::parser::validating::date_pskel;
  using ::xsde::cxx::parser::validating::date_pimpl;

  using ::xsde::cxx::parser::validating::date_time_pskel;
  using ::xsde::cxx::parser::validating::date_time_pimpl;

  using ::xsde::cxx::parser::validating::duration_pskel;
  using ::xsde::cxx::parser::validating::duration_pimpl;

  using ::xsde::cxx::parser::validating::gday_pskel;
  using ::xsde::cxx::parser::validating::gday_pimpl;

  using ::xsde::cxx::parser::validating::gmonth_pskel;
  using ::xsde::cxx::parser::validating::gmonth_pimpl;

  using ::xsde::cxx::parser::validating::gmonth_day_pskel;
  using ::xsde::cxx::parser::validating::gmonth_day_pimpl;

  using ::xsde::cxx::parser::validating::gyear_pskel;
  using ::xsde::cxx::parser::validating::gyear_pimpl;

  using ::xsde::cxx::parser::validating::gyear_month_pskel;
  using ::xsde::cxx::parser::validating::gyear_month_pimpl;

  using ::xsde::cxx::parser::validating::time_pskel;
  using ::xsde::cxx::parser::validating::time_pimpl;

  // Read-only string.
  //
  using ::xsde::cxx::ro_string;

  // Error codes.
  //
  typedef xsde::cxx::parser::expat::xml_error parser_xml_error;
  typedef xsde::cxx::schema_error parser_schema_error;

  // Exceptions.
  //
  typedef xsde::cxx::parser::exception parser_exception;
  typedef xsde::cxx::parser::xml parser_xml;
  typedef xsde::cxx::parser::schema parser_schema;

  // Document parser.
  //
  using xsde::cxx::parser::expat::document_pimpl;

  // Parser context.
  //
  typedef xsde::cxx::parser::context parser_context;
}

#include "common-pskel.hpp"

#include "phenotype_common-pskel.hpp"

#include "mesh-pskel.hpp"

namespace state
{
  class phase_name_pskel: public ::xml_schema::string_pskel
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    // Attributes.
    //
    virtual void
    GO_ID (const ::std::string&);

    virtual ::state::phase_name
    post_phase_name () = 0;

    // Parser construction API.
    //
    void
    parsers (::xml_schema::string_pskel& /* GO_ID */);

    // Individual attribute parsers.
    //
    void
    GO_ID_parser (::xml_schema::string_pskel&);

    virtual void
    _reset ();

    // Constructor.
    //
    phase_name_pskel (::xml_schema::string_pskel* tiein);

    public:
    static const char*
    _static_type ();

    virtual const char*
    _dynamic_type () const;

    // Implementation details.
    //
    virtual ::std::string
    post_string ();

    protected:
    phase_name_pskel* phase_name_impl_;
    phase_name_pskel (phase_name_pskel*, void*);

    protected:
    virtual bool
    _attribute_impl_phase_one (const ::xsde::cxx::ro_string&,
                               const ::xsde::cxx::ro_string&,
                               const ::xsde::cxx::ro_string&);


    protected:
    ::xml_schema::string_pskel* GO_ID_parser_;
  };

  class phase_pskel: public ::xsde::cxx::parser::validating::complex_content
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    // Elements.
    //
    virtual void
    model_name (const ::std::string&);

    virtual void
    phase_name (const ::state::phase_name&);

    virtual void
    cell_cycle_model_index (unsigned short);

    virtual void
    cell_cycle_phase_index (unsigned short);

    virtual void
    elapsed_time (::common::units_decimal*);

    virtual void
    custom (::common::custom*);

    virtual ::state::phase*
    post_phase () = 0;

    // Parser construction API.
    //
    void
    parsers (::xml_schema::string_pskel& /* model_name */,
             ::state::phase_name_pskel& /* phase_name */,
             ::xml_schema::unsigned_short_pskel& /* cell_cycle_model_index */,
             ::xml_schema::unsigned_short_pskel& /* cell_cycle_phase_index */,
             ::common::units_decimal_pskel& /* elapsed_time */,
             ::common::custom_pskel& /* custom */);

    void
    parser_maps (::xml_schema::parser_map& /* model_name */,
                 ::xml_schema::parser_map& /* phase_name */,
                 ::xml_schema::parser_map& /* cell_cycle_model_index */,
                 ::xml_schema::parser_map& /* cell_cycle_phase_index */,
                 ::xml_schema::parser_map& /* elapsed_time */,
                 ::xml_schema::parser_map& /* custom */);

    // Individual element parsers.
    //
    void
    model_name_parser (::xml_schema::string_pskel&);

    void
    model_name_parser (::xml_schema::parser_map&);

    void
    phase_name_parser (::state::phase_name_pskel&);

    void
    phase_name_parser (::xml_schema::parser_map&);

    void
    cell_cycle_model_index_parser (::xml_schema::unsigned_short_pskel&);

    void
    cell_cycle_model_index_parser (::xml_schema::parser_map&);

    void
    cell_cycle_phase_index_parser (::xml_schema::unsigned_short_pskel&);

    void
    cell_cycle_phase_index_parser (::xml_schema::parser_map&);

    void
    elapsed_time_parser (::common::units_decimal_pskel&);

    void
    elapsed_time_parser (::xml_schema::parser_map&);

    void
    custom_parser (::common::custom_pskel&);

    void
    custom_parser (::xml_schema::parser_map&);

    virtual void
    _reset ();

    // Constructor.
    //
    phase_pskel ();

    public:
    static const char*
    _static_type ();

    virtual const char*
    _dynamic_type () const;

    // Implementation details.
    //
    protected:
    phase_pskel* phase_impl_;
    phase_pskel (phase_pskel*, void*);

    protected:
    virtual bool
    _start_element_impl (const ::xsde::cxx::ro_string&,
                         const ::xsde::cxx::ro_string&,
                         const char*);

    virtual bool
    _end_element_impl (const ::xsde::cxx::ro_string&,
                       const ::xsde::cxx::ro_string&);

    protected:
    ::xml_schema::string_pskel* model_name_parser_;
    ::xml_schema::parser_map* model_name_parser_map_;

    ::state::phase_name_pskel* phase_name_parser_;
    ::xml_schema::parser_map* phase_name_parser_map_;

    ::xml_schema::unsigned_short_pskel* cell_cycle_model_index_parser_;
    ::xml_schema::parser_map* cell_cycle_model_index_parser_map_;

    ::xml_schema::unsigned_short_pskel* cell_cycle_phase_index_parser_;
    ::xml_schema::parser_map* cell_cycle_phase_index_parser_map_;

    ::common::units_decimal_pskel* elapsed_time_parser_;
    ::xml_schema::parser_map* elapsed_time_parser_map_;

    ::common::custom_pskel* custom_parser_;
    ::xml_schema::parser_map* custom_parser_map_;


    public:
    struct v_state_descr_
    {
      void (::state::phase_pskel::*func) (
        unsigned long&,
        unsigned long&,
        const ::xsde::cxx::ro_string&,
        const ::xsde::cxx::ro_string&,
        const char*,
        bool);
      unsigned long state;
      unsigned long count;
    };

    struct v_state_
    {
      v_state_descr_ data[2UL];
      unsigned long size;
    };

    protected:
    v_state_ v_state_first_;
    ::xsde::cxx::stack v_state_stack_;

    virtual void
    _pre_e_validate ();

    virtual void
    _post_e_validate ();

    void
    all_0 (unsigned long&,
           unsigned char*,
           const ::xsde::cxx::ro_string&,
           const ::xsde::cxx::ro_string&,
           const char*,
           bool);

    unsigned char v_all_first_[6UL];
    ::xsde::cxx::parser::validating::all_stack v_all_count_;
  };

  class orientation_formalism_pskel: public ::xml_schema::string_pskel
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    virtual ::state::orientation_formalism
    post_orientation_formalism () = 0;

    public:
    static const char*
    _static_type ();

    virtual const char*
    _dynamic_type () const;

    // Constructor.
    //
    orientation_formalism_pskel (::xml_schema::string_pskel* tiein);

    // Implementation details.
    //
    virtual ::std::string
    post_string ();

    protected:
    orientation_formalism_pskel* orientation_formalism_impl_;
    orientation_formalism_pskel (orientation_formalism_pskel*, void*);

    protected:
    static const char* const _xsde_orientation_formalism_pskel_enums_[7UL];
  };

  class orientation_pskel: public ::common::units_double_list_pskel
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    // Attributes.
    //
    virtual void
    formalism (const ::state::orientation_formalism&);

    virtual ::state::orientation*
    post_orientation () = 0;

    // Parser construction API.
    //
    void
    parsers (::xml_schema::double_pskel& /* double_list item */,
             ::xml_schema::string_pskel& /* units */,
             ::xml_schema::string_pskel& /* measurement_type */,
             ::xml_schema::double_pskel& /* uncertainty */,
             ::xml_schema::double_pskel& /* negative_uncertainty */,
             ::xml_schema::double_pskel& /* positive_uncertainty */,
             ::xml_schema::double_pskel& /* uncertainty_percentage */,
             ::xml_schema::double_pskel& /* negative_uncertainty_percentage */,
             ::xml_schema::double_pskel& /* positive_uncertainty_percentage */,
             ::xml_schema::double_pskel& /* median */,
             ::xml_schema::double_pskel& /* standard_deviation */,
             ::common::two_doubles_pskel& /* interquartile_range */,
             ::common::two_doubles_pskel& /* range */,
             ::xml_schema::double_pskel& /* min */,
             ::xml_schema::double_pskel& /* max */,
             ::xml_schema::double_pskel& /* standard_error */,
             ::xml_schema::double_pskel& /* standard_error_of_the_mean */,
             ::xml_schema::int_pskel& /* number_obs */,
             ::xml_schema::double_pskel& /* skewnesss */,
             ::xml_schema::double_pskel& /* kurtosis */,
             ::state::orientation_formalism_pskel& /* formalism */);

    // Individual attribute parsers.
    //
    void
    formalism_parser (::state::orientation_formalism_pskel&);

    virtual void
    _reset ();

    // Constructor.
    //
    orientation_pskel (::common::units_double_list_pskel* tiein);

    public:
    static const char*
    _static_type ();

    virtual const char*
    _dynamic_type () const;

    // Implementation details.
    //
    virtual ::common::units_double_list*
    post_units_double_list ();

    protected:
    orientation_pskel* orientation_impl_;
    orientation_pskel (orientation_pskel*, void*);

    protected:
    virtual bool
    _attribute_impl_phase_one (const ::xsde::cxx::ro_string&,
                               const ::xsde::cxx::ro_string&,
                               const ::xsde::cxx::ro_string&);


    protected:
    ::state::orientation_formalism_pskel* formalism_parser_;
  };

  class cell_parts_pskel: public ::xsde::cxx::parser::validating::complex_content
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    // Attributes.
    //
    virtual void
    name (const ::std::string&);

    virtual void
    ID (unsigned int);

    // Elements.
    //
    virtual void
    orientation (::state::orientation*);

    virtual void
    position (::common::units_double_list*);

    virtual void
    velocity (::common::units_double_list*);

    virtual void
    voxels (::mesh::int_list_xpath*);

    virtual void
    cell_part (::state::cell_parts*);

    virtual void
    custom (::common::custom*);

    virtual ::state::cell_parts*
    post_cell_parts () = 0;

    // Parser construction API.
    //
    void
    parsers (::xml_schema::string_pskel& /* name */,
             ::xml_schema::unsigned_int_pskel& /* ID */,
             ::state::orientation_pskel& /* orientation */,
             ::common::units_double_list_pskel& /* position */,
             ::common::units_double_list_pskel& /* velocity */,
             ::mesh::int_list_xpath_pskel& /* voxels */,
             ::state::cell_parts_pskel& /* cell_part */,
             ::common::custom_pskel& /* custom */);

    void
    parser_maps (::xml_schema::parser_map& /* orientation */,
                 ::xml_schema::parser_map& /* position */,
                 ::xml_schema::parser_map& /* velocity */,
                 ::xml_schema::parser_map& /* voxels */,
                 ::xml_schema::parser_map& /* cell_part */,
                 ::xml_schema::parser_map& /* custom */);

    // Individual attribute parsers.
    //
    void
    name_parser (::xml_schema::string_pskel&);

    void
    ID_parser (::xml_schema::unsigned_int_pskel&);

    // Individual element parsers.
    //
    void
    orientation_parser (::state::orientation_pskel&);

    void
    orientation_parser (::xml_schema::parser_map&);

    void
    position_parser (::common::units_double_list_pskel&);

    void
    position_parser (::xml_schema::parser_map&);

    void
    velocity_parser (::common::units_double_list_pskel&);

    void
    velocity_parser (::xml_schema::parser_map&);

    void
    voxels_parser (::mesh::int_list_xpath_pskel&);

    void
    voxels_parser (::xml_schema::parser_map&);

    void
    cell_part_parser (::state::cell_parts_pskel&);

    void
    cell_part_parser (::xml_schema::parser_map&);

    void
    custom_parser (::common::custom_pskel&);

    void
    custom_parser (::xml_schema::parser_map&);

    virtual void
    _reset ();

    // Constructor.
    //
    cell_parts_pskel ();

    public:
    static const char*
    _static_type ();

    virtual const char*
    _dynamic_type () const;

    // Implementation details.
    //
    protected:
    cell_parts_pskel* cell_parts_impl_;
    cell_parts_pskel (cell_parts_pskel*, void*);

    protected:
    virtual bool
    _start_element_impl (const ::xsde::cxx::ro_string&,
                         const ::xsde::cxx::ro_string&,
                         const char*);

    virtual bool
    _end_element_impl (const ::xsde::cxx::ro_string&,
                       const ::xsde::cxx::ro_string&);

    protected:
    virtual bool
    _attribute_impl_phase_one (const ::xsde::cxx::ro_string&,
                               const ::xsde::cxx::ro_string&,
                               const ::xsde::cxx::ro_string&);


    protected:
    ::xml_schema::string_pskel* name_parser_;
    ::xml_schema::unsigned_int_pskel* ID_parser_;
    ::state::orientation_pskel* orientation_parser_;
    ::xml_schema::parser_map* orientation_parser_map_;

    ::common::units_double_list_pskel* position_parser_;
    ::xml_schema::parser_map* position_parser_map_;

    ::common::units_double_list_pskel* velocity_parser_;
    ::xml_schema::parser_map* velocity_parser_map_;

    ::mesh::int_list_xpath_pskel* voxels_parser_;
    ::xml_schema::parser_map* voxels_parser_map_;

    ::state::cell_parts_pskel* cell_part_parser_;
    ::xml_schema::parser_map* cell_part_parser_map_;

    ::common::custom_pskel* custom_parser_;
    ::xml_schema::parser_map* custom_parser_map_;


    public:
    struct v_state_descr_
    {
      void (::state::cell_parts_pskel::*func) (
        unsigned long&,
        unsigned long&,
        const ::xsde::cxx::ro_string&,
        const ::xsde::cxx::ro_string&,
        const char*,
        bool);
      unsigned long state;
      unsigned long count;
    };

    struct v_state_
    {
      v_state_descr_ data[3UL];
      unsigned long size;
    };

    protected:
    v_state_ v_state_first_;
    ::xsde::cxx::stack v_state_stack_;

    virtual void
    _pre_e_validate ();

    virtual void
    _post_e_validate ();

    void
    sequence_1 (unsigned long&,
                unsigned long&,
                const ::xsde::cxx::ro_string&,
                const ::xsde::cxx::ro_string&,
                const char*,
                bool);

    void
    sequence_0 (unsigned long&,
                unsigned long&,
                const ::xsde::cxx::ro_string&,
                const ::xsde::cxx::ro_string&,
                const char*,
                bool);

    protected:
    struct v_state_attr_
    {
      bool name;
    };

    v_state_attr_ v_state_attr_first_;
    ::xsde::cxx::stack v_state_attr_stack_;

    virtual void
    _pre_a_validate ();

    virtual void
    _post_a_validate ();
  };

  class state_pskel: public ::xsde::cxx::parser::validating::complex_content
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    // Elements.
    //
    virtual void
    orientation (::state::orientation*);

    virtual void
    position (::common::units_double_list*);

    virtual void
    velocity (::common::units_double_list*);

    virtual void
    voxels (::mesh::int_list_xpath*);

    virtual void
    cell_part (::state::cell_parts*);

    virtual void
    phase (::state::phase*);

    virtual void
    adhered_cells (::state::list_of_adhered_cells*);

    virtual void
    custom (::common::custom*);

    virtual ::state::state*
    post_state () = 0;

    // Parser construction API.
    //
    void
    parsers (::state::orientation_pskel& /* orientation */,
             ::common::units_double_list_pskel& /* position */,
             ::common::units_double_list_pskel& /* velocity */,
             ::mesh::int_list_xpath_pskel& /* voxels */,
             ::state::cell_parts_pskel& /* cell_part */,
             ::state::phase_pskel& /* phase */,
             ::state::list_of_adhered_cells_pskel& /* adhered_cells */,
             ::common::custom_pskel& /* custom */);

    void
    parser_maps (::xml_schema::parser_map& /* orientation */,
                 ::xml_schema::parser_map& /* position */,
                 ::xml_schema::parser_map& /* velocity */,
                 ::xml_schema::parser_map& /* voxels */,
                 ::xml_schema::parser_map& /* cell_part */,
                 ::xml_schema::parser_map& /* phase */,
                 ::xml_schema::parser_map& /* adhered_cells */,
                 ::xml_schema::parser_map& /* custom */);

    // Individual element parsers.
    //
    void
    orientation_parser (::state::orientation_pskel&);

    void
    orientation_parser (::xml_schema::parser_map&);

    void
    position_parser (::common::units_double_list_pskel&);

    void
    position_parser (::xml_schema::parser_map&);

    void
    velocity_parser (::common::units_double_list_pskel&);

    void
    velocity_parser (::xml_schema::parser_map&);

    void
    voxels_parser (::mesh::int_list_xpath_pskel&);

    void
    voxels_parser (::xml_schema::parser_map&);

    void
    cell_part_parser (::state::cell_parts_pskel&);

    void
    cell_part_parser (::xml_schema::parser_map&);

    void
    phase_parser (::state::phase_pskel&);

    void
    phase_parser (::xml_schema::parser_map&);

    void
    adhered_cells_parser (::state::list_of_adhered_cells_pskel&);

    void
    adhered_cells_parser (::xml_schema::parser_map&);

    void
    custom_parser (::common::custom_pskel&);

    void
    custom_parser (::xml_schema::parser_map&);

    virtual void
    _reset ();

    // Constructor.
    //
    state_pskel ();

    public:
    static const char*
    _static_type ();

    virtual const char*
    _dynamic_type () const;

    // Implementation details.
    //
    protected:
    state_pskel* state_impl_;
    state_pskel (state_pskel*, void*);

    protected:
    virtual bool
    _start_element_impl (const ::xsde::cxx::ro_string&,
                         const ::xsde::cxx::ro_string&,
                         const char*);

    virtual bool
    _end_element_impl (const ::xsde::cxx::ro_string&,
                       const ::xsde::cxx::ro_string&);

    protected:
    ::state::orientation_pskel* orientation_parser_;
    ::xml_schema::parser_map* orientation_parser_map_;

    ::common::units_double_list_pskel* position_parser_;
    ::xml_schema::parser_map* position_parser_map_;

    ::common::units_double_list_pskel* velocity_parser_;
    ::xml_schema::parser_map* velocity_parser_map_;

    ::mesh::int_list_xpath_pskel* voxels_parser_;
    ::xml_schema::parser_map* voxels_parser_map_;

    ::state::cell_parts_pskel* cell_part_parser_;
    ::xml_schema::parser_map* cell_part_parser_map_;

    ::state::phase_pskel* phase_parser_;
    ::xml_schema::parser_map* phase_parser_map_;

    ::state::list_of_adhered_cells_pskel* adhered_cells_parser_;
    ::xml_schema::parser_map* adhered_cells_parser_map_;

    ::common::custom_pskel* custom_parser_;
    ::xml_schema::parser_map* custom_parser_map_;


    public:
    struct v_state_descr_
    {
      void (::state::state_pskel::*func) (
        unsigned long&,
        unsigned long&,
        const ::xsde::cxx::ro_string&,
        const ::xsde::cxx::ro_string&,
        const char*,
        bool);
      unsigned long state;
      unsigned long count;
    };

    struct v_state_
    {
      v_state_descr_ data[3UL];
      unsigned long size;
    };

    protected:
    v_state_ v_state_first_;
    ::xsde::cxx::stack v_state_stack_;

    virtual void
    _pre_e_validate ();

    virtual void
    _post_e_validate ();

    void
    sequence_1 (unsigned long&,
                unsigned long&,
                const ::xsde::cxx::ro_string&,
                const ::xsde::cxx::ro_string&,
                const char*,
                bool);

    void
    sequence_0 (unsigned long&,
                unsigned long&,
                const ::xsde::cxx::ro_string&,
                const ::xsde::cxx::ro_string&,
                const char*,
                bool);
  };

  class adhered_cell_pskel: public ::xsde::cxx::parser::validating::complex_content
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    // Elements.
    //
    virtual void
    ID (unsigned int);

    virtual void
    contact_area (::common::units_decimal_nonnegative*);

    virtual void
    contact (::phenotype_common::cross_section*);

    virtual void
    custom (::common::custom*);

    virtual ::state::adhered_cell*
    post_adhered_cell () = 0;

    // Parser construction API.
    //
    void
    parsers (::xml_schema::unsigned_int_pskel& /* ID */,
             ::common::units_decimal_nonnegative_pskel& /* contact_area */,
             ::phenotype_common::cross_section_pskel& /* contact */,
             ::common::custom_pskel& /* custom */);

    void
    parser_maps (::xml_schema::parser_map& /* ID */,
                 ::xml_schema::parser_map& /* contact_area */,
                 ::xml_schema::parser_map& /* contact */,
                 ::xml_schema::parser_map& /* custom */);

    // Individual element parsers.
    //
    void
    ID_parser (::xml_schema::unsigned_int_pskel&);

    void
    ID_parser (::xml_schema::parser_map&);

    void
    contact_area_parser (::common::units_decimal_nonnegative_pskel&);

    void
    contact_area_parser (::xml_schema::parser_map&);

    void
    contact_parser (::phenotype_common::cross_section_pskel&);

    void
    contact_parser (::xml_schema::parser_map&);

    void
    custom_parser (::common::custom_pskel&);

    void
    custom_parser (::xml_schema::parser_map&);

    virtual void
    _reset ();

    // Constructor.
    //
    adhered_cell_pskel ();

    public:
    static const char*
    _static_type ();

    virtual const char*
    _dynamic_type () const;

    // Implementation details.
    //
    protected:
    adhered_cell_pskel* adhered_cell_impl_;
    adhered_cell_pskel (adhered_cell_pskel*, void*);

    protected:
    virtual bool
    _start_element_impl (const ::xsde::cxx::ro_string&,
                         const ::xsde::cxx::ro_string&,
                         const char*);

    virtual bool
    _end_element_impl (const ::xsde::cxx::ro_string&,
                       const ::xsde::cxx::ro_string&);

    protected:
    ::xml_schema::unsigned_int_pskel* ID_parser_;
    ::xml_schema::parser_map* ID_parser_map_;

    ::common::units_decimal_nonnegative_pskel* contact_area_parser_;
    ::xml_schema::parser_map* contact_area_parser_map_;

    ::phenotype_common::cross_section_pskel* contact_parser_;
    ::xml_schema::parser_map* contact_parser_map_;

    ::common::custom_pskel* custom_parser_;
    ::xml_schema::parser_map* custom_parser_map_;


    public:
    struct v_state_descr_
    {
      void (::state::adhered_cell_pskel::*func) (
        unsigned long&,
        unsigned long&,
        const ::xsde::cxx::ro_string&,
        const ::xsde::cxx::ro_string&,
        const char*,
        bool);
      unsigned long state;
      unsigned long count;
    };

    struct v_state_
    {
      v_state_descr_ data[2UL];
      unsigned long size;
    };

    protected:
    v_state_ v_state_first_;
    ::xsde::cxx::stack v_state_stack_;

    virtual void
    _pre_e_validate ();

    virtual void
    _post_e_validate ();

    void
    sequence_0 (unsigned long&,
                unsigned long&,
                const ::xsde::cxx::ro_string&,
                const ::xsde::cxx::ro_string&,
                const char*,
                bool);
  };

  class list_of_adhered_cells_pskel: public ::xsde::cxx::parser::validating::complex_content
  {
    public:
    // Parser callbacks. Override them in your implementation.
    //
    // virtual void
    // pre ();

    // Elements.
    //
    virtual void
    adhered_cell (::state::adhered_cell*);

    virtual void
    custom (::common::custom*);

    virtual ::state::list_of_adhered_cells*
    post_list_of_adhered_cells () = 0;

    // Parser construction API.
    //
    void
    parsers (::state::adhered_cell_pskel& /* adhered_cell */,
             ::common::custom_pskel& /* custom */);

    void
    parser_maps (::xml_schema::parser_map& /* adhered_cell */,
                 ::xml_schema::parser_map& /* custom */);

    // Individual element parsers.
    //
    void
    adhered_cell_parser (::state::adhered_cell_pskel&);

    void
    adhered_cell_parser (::xml_schema::parser_map&);

    void
    custom_parser (::common::custom_pskel&);

    void
    custom_parser (::xml_schema::parser_map&);

    virtual void
    _reset ();

    // Constructor.
    //
    list_of_adhered_cells_pskel ();

    public:
    static const char*
    _static_type ();

    virtual const char*
    _dynamic_type () const;

    // Implementation details.
    //
    protected:
    list_of_adhered_cells_pskel* list_of_adhered_cells_impl_;
    list_of_adhered_cells_pskel (list_of_adhered_cells_pskel*, void*);

    protected:
    virtual bool
    _start_element_impl (const ::xsde::cxx::ro_string&,
                         const ::xsde::cxx::ro_string&,
                         const char*);

    virtual bool
    _end_element_impl (const ::xsde::cxx::ro_string&,
                       const ::xsde::cxx::ro_string&);

    protected:
    ::state::adhered_cell_pskel* adhered_cell_parser_;
    ::xml_schema::parser_map* adhered_cell_parser_map_;

    ::common::custom_pskel* custom_parser_;
    ::xml_schema::parser_map* custom_parser_map_;


    public:
    struct v_state_descr_
    {
      void (::state::list_of_adhered_cells_pskel::*func) (
        unsigned long&,
        unsigned long&,
        const ::xsde::cxx::ro_string&,
        const ::xsde::cxx::ro_string&,
        const char*,
        bool);
      unsigned long state;
      unsigned long count;
    };

    struct v_state_
    {
      v_state_descr_ data[2UL];
      unsigned long size;
    };

    protected:
    v_state_ v_state_first_;
    ::xsde::cxx::stack v_state_stack_;

    virtual void
    _pre_e_validate ();

    virtual void
    _post_e_validate ();

    void
    sequence_0 (unsigned long&,
                unsigned long&,
                const ::xsde::cxx::ro_string&,
                const ::xsde::cxx::ro_string&,
                const char*,
                bool);
  };
}

#include "state-pskel.ipp"

// Begin epilogue.
//
//
// End epilogue.

#include <xsde/cxx/post.hxx>

#endif // STATE_PSKEL_HPP
