MCDS_DIR  = lib/MultiCellDS/v1.0/v1.0.0
XSDE_DIR  = $(MCDS_DIR)/libMCDS/xsde
LIBCS_DIR = lib/libCellShape
CATCH2_DIR = lib/Catch2
HOOMD_DIR = lib/hoomd
MUSCLE3_DIR = lib/muscle3
TST_DIR   = src
QMAKE     = qmake
# Edit the above line as necessary, e.g., as follows:
#QMAKE    = /Applications/Qt5/6.4.0/macos/bin/qmake

MODELS = bin/vessel bin/qPotts bin/sorting bin/Act_model

.PHONY: all XSDE MCDS LIBCS Catch2 TST python mpi4py ecm docs
.PHONY: test clean clean_hoomd



# The models can not be compiled in parallel, because the qmake run for one
# model would overwrite the files generated by the qmake run for another
# model. So we tell make to build them one by one here.
.NOTPARALLEL: all
all: $(MODELS)

.NOTPARALLEL: with_adhesions
with_adhesions: $(MODELS) bin/adhesions ecm ymmsl/adhesions.ymmsl ymmsl/plot_state.ymmsl ymmsl/dump_state.ymmsl


# Dependencies

XSDE:
	$(MAKE) -C $(XSDE_DIR)

MCDS: XSDE
	$(MAKE) -C $(MCDS_DIR) objects

LIBCS: MCDS
	$(MAKE) -C $(LIBCS_DIR)

Catch2:
	$(MAKE) -C $(CATCH2_DIR)

MUSCLE3:
	$(MAKE) -C $(MUSCLE3_DIR)


# Python virtual environment and components

# Derive Python install location
PYTHON_VERSION = $(shell python -c 'import sys; print("python{}.{}".format(*sys.version_info[0:2]))')

# Python version number
PYTHON_VERNUM := $(wordlist 2,4,$(subst ., ,$(shell $(PYTHON_VERSION) --version 2>&1)))
PYVER_MAJOR := $(word 1,$(PYTHON_VERNUM))
PYVER_MINOR := $(word 2,$(PYTHON_VERNUM))

# Check the python version
PYVER_MAJOR_REQ :=3
PYVER_MINOR_MIN :=9
PYVER_MINOR_MAX :=11

PYVER_MINOR_MIN_OK := $(shell [ $(PYVER_MINOR) -ge $(PYVER_MINOR_MIN) ] && echo "1" || echo "0")
PYVER_MINOR_MAX_OK := $(shell [ $(PYVER_MINOR) -le $(PYVER_MINOR_MAX) ] && echo "1" || echo "0")

pyver:
	@echo "Python must be >= $(PYVER_MAJOR_REQ).$(PYVER_MINOR_MIN) and <= $(PYVER_MAJOR_REQ).$(PYVER_MINOR_MAX). Current Python is $(PYTHON_VERSION)."
	@if [ $(PYVER_MAJOR) -ne $(PYVER_MAJOR_REQ) ]; then \
		echo "Major version too low, python must be >= $(PYVER_MAJOR_REQ).$(PYVER_MINOR_MIN)".; \
		exit 1; \
	fi
	@if [ $(PYVER_MINOR_MIN_OK) -eq 1 ]; then \
		if [ $(PYVER_MINOR_MAX_OK) -eq 0 ]; then \
			echo "Minor version too high, python must be <= $(PYVER_MAJOR_REQ).$(PYVER_MINOR_MAX)".; \
			exit 1; \
		fi \
	else \
		echo "Minor version too low, python must be >= $(PYVER_MAJOR_REQ).$(PYVER_MINOR_MIN)".; \
		exit 1; \
	fi
	@echo "Python version is fine! Proceed."


VENV_PKG = venv/lib/$(PYTHON_VERSION)/site-packages

# Representative targets, we assume that if these are up to date, the corresponding
# object has been created successfully.
VENV = venv/bin/activate
VENV_NUMPY = $(VENV_PKG)/numpy/__init__.py
VENV_HOOMD = $(VENV_PKG)/hoomd/__init__.py

VENV_DOCS = venv_docs/bin/activate


# If MPI should be used, install mpi4py and compile hoomd with MPI enabled
ifdef ENABLE_MPI

$(info Enabling MPI. If you get compilation errors, check that you have)
$(info an MPI library like OpenMPI or MPICH installed, and that it)
$(info includes development tools and headers if applicable.)
$(info )
export HOOMD_BUILD_OPTIONS += -DENABLE_MPI=ON
python: mpi4py

endif  # ENABLE_MPI


# Due to dependency issues with Python3.12 and Muscle3, we create a VENV with the highest available python less than 3.12
# Numpy also got a major update recently, and some dependencies do not work with the newer version unfortunately.
$(VENV): pyver
	python3 -m venv venv

$(VENV_NUMPY): $(VENV)
	. venv/bin/activate && python3 -m pip install numpy==1.25.0

$(VENV_HOOMD): $(VENV) $(VENV_NUMPY)
	. venv/bin/activate && $(MAKE) -C $(HOOMD_DIR) install
	@# The hoomd installer doesn't touch the file, so we do it here so we don't keep
	@# reinstalling again and again.
	touch $(VENV_HOOMD)
	
$(VENV_DOCS):
	python3 -m venv venv_docs
	. venv_docs/bin/activate && python -m pip install -r ./doc/requirements.txt

docs: $(VENV_DOCS)
	cd doc; doxygen Doxyfile.in 
	. venv_docs/bin/activate && $(MAKE) -C doc html
	rm -r doc/docs/* || true
	mv doc/build/html doc/docs

mpi4py: $(VENV)
	. venv/bin/activate && python3 -m pip install mpi4py

python: $(VENV)
	. venv/bin/activate && python3 -m pip install --upgrade pip && python3 -m pip install -e . --verbose

pyqt5: $(VENV) $(VENV_NUMPY)
	. venv/bin/activate && python3 -m pip install PyQt5

py_ruamel: $(VENV) $(VENV_NUMPY)
	. venv/bin/activate && python3 -m pip install ruamel.yaml

ecm: $(VENV_HOOMD) python pyqt5 py_ruamel


# Models

bin/%: MCDS LIBCS
	cd $(TST_DIR) && $(QMAKE) $(@:bin/%=%).pro
	$(MAKE) -C $(TST_DIR)

bin/adhesions: MUSCLE3

ymmsl:
	mkdir ymmsl

ymmsl/%.ymmsl: src/models/%.ymmsl.in ymmsl
	sed -e 's&Tissue-Simulation-Toolkit&$(CURDIR)&g' $< >$@


# Tests

CATCH2_BASE = $(CATCH2_DIR)/catch2
export CATCH2_BASE

test: Catch2 MCDS LIBCS
	tox
	# Add new directories with C++ tests here and also below under clean:
	$(MAKE) -C $(TST_DIR)/adhesions/tests run_all_tests
	$(MAKE) -C $(TST_DIR)/cellular_potts/tests run_all_tests
	$(MAKE) -C $(TST_DIR)/spatial/tests run_all_tests
	$(MAKE) -C $(TST_DIR)/parameters/tests run_all_tests




# Cleanup

clean:
	$(MAKE) -C $(XSDE_DIR) clean

	# MCDS make clean is broken, so do it by hand here
	rm -f $(MCDS_DIR)/libMCDS/mcds_api/*.o $(MCDS_DIR)/libMCDS/mcds_api/*.a

	$(MAKE) -C $(LIBCS_DIR) clean
	$(MAKE) -C $(CATCH2_DIR) clean
	$(MAKE) -C $(MUSCLE3_DIR) clean

	# This fails if it hasn't been built and there's no Makefile, that's fine
	-$(MAKE) -C $(TST_DIR) clean
	rm -rf bin build_files/* $(TST_DIR)/Makefile $(TST_DIR)/.qmake.stash venv
	rm -rf build

	# Add new test directories here
	$(MAKE) -C $(TST_DIR)/adhesions/tests clean
	$(MAKE) -C $(TST_DIR)/cellular_potts/tests clean
	$(MAKE) -C $(TST_DIR)/spatial/tests clean
	$(MAKE) -C $(TST_DIR)/parameters/tests clean

	@echo
	@echo "Note: 'make clean' does not remove hoomd, because hoomd takes a long time to"
	@echo "recompile and you probably don't want to do that. If you do want to rebuild"
	@echo "hoomd, use 'make clean_hoomd' to clean it up."

clean_hoomd:
	$(MAKE) -C $(HOOMD_DIR) clean
