MCDS_DIR  = lib/MultiCellDS/v1.0/v1.0.0
XSDE_DIR  = $(MCDS_DIR)/libMCDS/xsde
LIBCS_DIR = lib/libCellShape
CATCH2_DIR = lib/Catch2
HOOMD_DIR = lib/hoomd
MUSCLE3_DIR = lib/muscle3
TST_DIR   = src
QMAKE     = qmake
# Edit the above line as necessary, e.g., as follows:
#QMAKE    = /Applications/Qt5/6.4.0/macos/bin/qmake

MODELS = bin/vessel bin/qPotts bin/sorting bin/Act_model

.PHONY: all XSDE MCDS LIBCS Catch2 python_components python_dependencies TST
.PHONY: test clean clean_hoomd


# The models can not be compiled in parallel, because the qmake run for one
# model would overwrite the files generated by the qmake run for another
# model. So we tell make to build them one by one here.
.NOTPARALLEL: all
all: $(MODELS)

.NOTPARALLEL: with_adhesions
with_adhesions: $(MODELS) bin/adhesions


# Dependencies

XSDE:
	$(MAKE) -C $(XSDE_DIR)

MCDS: XSDE
	$(MAKE) -C $(MCDS_DIR) objects

LIBCS: MCDS
	$(MAKE) -C $(LIBCS_DIR)

Catch2:
	$(MAKE) -C $(CATCH2_DIR)

MUSCLE3:
	$(MAKE) -C $(MUSCLE3_DIR)


# Python virtual environment and components

venv:
	python3 -m venv venv


python_dependencies: venv
	. venv/bin/activate && python3 -m pip install numpy
	. venv/bin/activate && $(MAKE) -C $(HOOMD_DIR) install


# Models

bin/%: MCDS LIBCS
	cd $(TST_DIR) && $(QMAKE) $(@:bin/%=%).pro
	$(MAKE) -C $(TST_DIR)

bin/adhesions: MUSCLE3


# Tests

CATCH2_BASE = $(CATCH2_DIR)/catch2
export CATCH2_BASE

test: Catch2 MCDS LIBCS
	# Add new directories with tests here and also below under clean:
	$(MAKE) -C $(TST_DIR)/adhesions/tests run_all_tests
	$(MAKE) -C $(TST_DIR)/cellular_potts/tests run_all_tests
	$(MAKE) -C $(TST_DIR)/util/tests run_all_tests
	$(MAKE) -C $(TST_DIR)/parameters/tests run_all_tests


# Cleanup

clean:
	$(MAKE) -C $(XSDE_DIR) clean

	# MCDS make clean is broken, so do it by hand here
	rm -f $(MCDS_DIR)/libMCDS/mcds_api/*.o $(MCDS_DIR)/libMCDS/mcds_api/*.a

	$(MAKE) -C $(LIBCS_DIR) clean
	$(MAKE) -C $(CATCH2_DIR) clean
	$(MAKE) -C $(MUSCLE3_DIR) clean

	# This fails if it hasn't been built and there's no Makefile, that's fine
	-$(MAKE) -C $(TST_DIR) clean
	rm -rf bin build_files/* $(TST_DIR)/Makefile $(TST_DIR)/.qmake.stash venv

	# Add new test directories here
	$(MAKE) -C $(TST_DIR)/adhesions/tests clean
	$(MAKE) -C $(TST_DIR)/cellular_potts/tests clean
	$(MAKE) -C $(TST_DIR)/util/tests clean
	$(MAKE) -C $(TST_DIR)/parameters/tests clean

	@echo
	@echo "Note: 'make clean' does not remove hoomd, because hoomd takes a long time to"
	@echo "recompile and you probably don't want to do that. If you do want to rebuild"
	@echo "hoomd, use 'make clean_hoomd' to clean it up."

clean_hoomd:
	$(MAKE) -C $(HOOMD_DIR) clean
