/* Generated - do not edit. */
#ifndef XSDE_CONFIG_H
#define XSDE_CONFIG_H
#define XSDE_PLATFORM_POSIX
#define XSDE_ARCH_WIDTH 32
#define XSDE_BYTEORDER 1234
#define XSDE_ENCODING_UTF8
#undef XSDE_ENCODING_ISO8859_1
#define XSDE_STL
#define XSDE_STL_ITERATOR
#define XSDE_IOSTREAM
#define XSDE_EXCEPTIONS
#define XSDE_LONGLONG
#define XSDE_SNPRINTF
#define XSDE_PARSER_VALIDATION
#define XSDE_SERIALIZER_VALIDATION
#undef XSDE_REUSE_STYLE_MIXIN
#define XSDE_REUSE_STYLE_TIEIN
#undef XSDE_REUSE_STYLE_NONE
#define XSDE_POLYMORPHIC
#define XSDE_PARSER_SMAP_BUCKETS 53UL
#define XSDE_PARSER_IMAP_BUCKETS 97UL
#define XSDE_SERIALIZER_SMAP_BUCKETS 53UL
#define XSDE_SERIALIZER_SMAP_BUCKET_BUCKETS 53UL
#define XSDE_SERIALIZER_IMAP_BUCKETS 97UL
#endif
