Dish Class Reference
The virtual Petri dish.
#include <dish.h>
Public Member Functions
Dish (void)
void Init (void)
Init defines the initial state of the virtual cell culture.
void ConstructorBody (void)
virtual ~Dish ()
void Plot (Graphics *g)
Plot the Dish to graphics window g.
int ZygoteArea (void) const
int Time (void) const
Returns the number of completed Monte Carlo Steps.
int CountCells (void) const
Returns the number of cells in the dish, excluding apoptosed cells.
void CellGrowthAndDivision (void)
Stretched induced cell growth and division.
int Area (void) const
. Returns the summed area of all cells in the dish
int TargetArea (void) const
Returns the summed of all cells target area in the dish.
int SizeX (void)
Returns the horizontal size of the dish.
int SizeY (void)
Returns the horizontal size of the dish.
Cell & getCell (int c)
Returns a reference to cell number `c`.
void ClearGrads (void)
void MeasureChemConcentrations (void)
Public Attributes
PDE * PDEfield
CellularPotts * CPM
Protected Member Functions
void SetCellOwner (Cell &which_cell)
Assign a the cell to the current Dish.
Protected Attributes
std::vector< Cell > cell
The cells in the Petri dish; accessible to derived classes.
Friends
class Info
Detailed Description
The virtual Petri dish.
Hosts the cells with states and the CA-plane.
Constructor & Destructor Documentation
Dish::Dish (void)
References Parameter::n_chem, Parameter::sizex, Parameter::sizey, and Parameter::target_area.
Dish::~Dish () [virtual]
Member Function Documentation
int Dish::Area (void) const
. Returns the summed area of all cells in the dish
void Dish::CellGrowthAndDivision (void)
Stretched induced cell growth and division.
See Hogeweg (2000), Journal of Theoretical Biology.
Find stretched cells, and increase their target area. Find enlarged cells, and divide them.
References Cell::IncrementTargetArea().
void Dish::ClearGrads (void)
void Dish::ConstructorBody (void)
References Cell::maxsigma.
int Dish::CountCells (void) const
Returns the number of cells in the dish, excluding apoptosed cells.
Cell& Dish::getCell (int c) [inline]
Returns a reference to cell number `c`.
References cell.
void Dish::Init (void)
Init defines the initial state of the virtual cell culture.
Define Init() in your main file describing the simulation set up, within the block INIT { }. See for examples vessel.cpp and sorting.cpp.
void Dish::MeasureChemConcentrations (void)
References Cell::Area(), Cell::chem, and Parameter::n_chem.
void Dish::Plot (Graphics * g)
Plot the Dish to graphics window g.
Simply calls CPM->Plot.
void Dish::SetCellOwner (Cell & which_cell) [protected]
Assign a the cell to the current Dish.
References Cell::owner.
int Dish::SizeX (void)
Returns the horizontal size of the dish.
int Dish::SizeY (void)
Returns the horizontal size of the dish.
int Dish::TargetArea (void) const
Returns the summed of all cells target area in the dish.
int Dish::Time (void) const
Returns the number of completed Monte Carlo Steps.
Referenced by Cell::CellBirth().
int Dish::ZygoteArea (void) const
Friends And Related Function Documentation
friend class Info [friend]
Member Data Documentation
std::vector<Cell> Dish::cell [protected]
The cells in the Petri dish; accessible to derived classes.
Referenced by getCell().
CellularPotts* Dish::CPM
PDE* Dish::PDEfield
The documentation for this class was generated from the following files:
dish.h
dish.cpp