Info Class Reference
Enables interactive querying of the simulation.
#include <info.h>
Public Member Functions
Info (Dish &dish, Graphics &graphics, std::ostream &out=std::cout)
Constructs and Info class dish with specified graphics window.
void Menu (void)
Reads out key presses in the Graphics window and interprets them.
void WriteCOM (int cell_id, std::ostream &out=std::cout)
Writes center of mass of cell `cell_id` to stream out.
Cell & ClickCell (Graphics *g)
Waits until the user clicks a cell and returns a reference to it.
Detailed Description
Enables interactive querying of the simulation.
Only using key presses, to be defined in Info::Menu().
Right-click menu in future Qt-linked versions?
Constructor & Destructor Documentation
Info::Info (Dish & dish, Graphics & graphics, std::ostream & out = std::cout)
Constructs and Info class dish with specified graphics window.
Parameters
dish The virtual Petri dish to query.
graphics The Graphics window displaying the dish.
out (optional) Stream into which info is written. Default: console.
References Info().
Referenced by Info().
Member Function Documentation
Cell & Info::ClickCell (Graphics * g)
Waits until the user clicks a cell and returns a reference to it.
References Graphics::GetXYCoo().
void Info::Menu (void)
Reads out key presses in the Graphics window and interprets them.
If you want to define extra interactive queries, redefine this method.
If you want a nice GUI menu, reimplement this method.
References Cell::Area(), Cell::Colour(), Parameter::lambda, Cell::MeasureCellSize(), par, ReadDouble(), Cell::SetTargetArea(), Cell::SetTargetLength(), Cell::setTau(), Cell::Sigma(), Parameter::size_init_cells, Cell::TargetArea(), and YesNoP().
void Info::WriteCOM (int cell_id, std::ostream & out = std::cout)
Writes center of mass of cell `cell_id` to stream out.
The documentation for this class was generated from the following files:
info.h
info.cpp