crash.h File Reference
Functions
void StartSIGINTHandling ()
void HandleSIGINT (int dummy)
void StartSIGSEGVHandling ()
void HandleSIGSEGV (int dummy)
void NiceMessage ()
void MemoryWarning (void)
void Crash (char *message)
Function Documentation
void Crash (char * message)
Referenced by HandleSIGINT(), HandleSIGSEGV(), and MemoryWarning().
void HandleSIGINT (int dummy)
References Crash().
Referenced by StartSIGINTHandling().
void HandleSIGSEGV (int dummy)
References Crash().
Referenced by StartSIGSEGVHandling().
void MemoryWarning (void)
References Crash().
Referenced by CellularPotts::AllocateSigma(), PDE::AllocateSigma(), CellularPotts::FindCellDirections(), CellularPotts::GrowInCells(), CellularPotts::ReadZygotePicture(), and CellularPotts::SearchNandPlot().
void NiceMessage ()
Referenced by StartSIGINTHandling().
void StartSIGINTHandling ()
References HandleSIGINT(), and NiceMessage().
void StartSIGSEGVHandling ()
References HandleSIGSEGV().