hull.h File Reference
Classes
class Point
Functions
int chainHull_2D (Point *P, int n, Point *H)
Function Documentation
int chainHull_2D (Point * P, int n, Point * H)
References isLeft(), and Point::x.
Referenced by CellularPotts::Compactness(), and CellularPotts::DrawConvexHull().