hull.cpp File Reference
#include `hull.h`
*
Functions
float isLeft (Point P0, Point P1, Point P2)
int chainHull_2D (Point *P, int n, Point *H)
Function Documentation
int chainHull_2D (Point * P, int n, Point * H)
References isLeft(), and Point::x.
Referenced by CellularPotts::Compactness(), and CellularPotts::DrawConvexHull().
float isLeft (Point P0, Point P1, Point P2) [inline]
References Point::x, and Point::y.
Referenced by chainHull_2D().