misc.cpp File Reference
#include <stdio.h>
*
#include <locale.h>
*
#include <stdlib.h>
*
#include <cstring>
*
#include `sticky.h`
*
Functions
int ReadNumber (FILE *file, int *number)
int ReadDouble (FILE *file, double *number)
int FileExists (FILE **fp, const char *fname, const char *ftype)
int YesNoP (const char *message)
char * GetFileName (const char *message, const char *ftype)
Function Documentation
int FileExists (FILE ** fp, const char * fname, const char * ftype)
References FALSE, and TRUE.
Referenced by GetFileName().
char* GetFileName (const char * message, const char * ftype)
References FALSE, FileExists(), TRUE, and YesNoP().
int ReadDouble (FILE * file, double * number)
References OK, and REMARK.
Referenced by Info::Menu().
int ReadNumber (FILE * file, int * number)
PUBLIC
References OK, and REMARK.
int YesNoP (const char * message)
Referenced by GetFileName(), and Info::Menu().