output.h File Reference
Macros
#define MESS_BUF_SIZE 160
#define FALSE 0
#define TRUE 1
Functions
int OpenFileAndCheckExistance (FILE **fp, const char *fname, char *ftype)
int YesNoP (const char *message)
FILE * OpenWriteFile (const char *filename)
FILE * OpenGZippedWriteFile (const char *filename)
FILE * OpenReadFile (const char *filename)
char * ReadLine (FILE *fp)
void CheckFile (FILE *fp)
int FileExistsP (const char *fname)
char * Chext (char *filename)
void MakeDir (const char *dirname)
bool CanWeWriteP (char *filename)
Macro Definition Documentation
#define FALSE 0
#define MESS_BUF_SIZE 160
#define TRUE 1
Function Documentation
bool CanWeWriteP (char * filename)
void CheckFile (FILE * fp)
References errno, and error().
Referenced by ReadLine().
char* Chext (char * filename)
int FileExistsP (const char * fname)
References FALSE, and TRUE.
Referenced by OpenWriteFile().
void MakeDir (const char * dirname)
int OpenFileAndCheckExistance (FILE ** fp, const char * fname, char * ftype)
References FALSE, and TRUE.
Referenced by OpenReadFile().
FILE* OpenGZippedWriteFile (const char * filename)
FILE* OpenReadFile (const char * filename)
References FALSE, and OpenFileAndCheckExistance().
Referenced by Parameter::Read().
FILE* OpenWriteFile (const char * filename)
References FileExistsP(), FNAMESIZE, and TRUE.
char* ReadLine (FILE * fp)
References CheckFile(), errno, error(), INITIAL_BUFSIZE, and MEMORYCHECK.
Referenced by SearchToken(), and SkipLine().
int YesNoP (const char * message)
References FALSE, and TRUE.
Referenced by GetFileName(), and Info::Menu().