output.cpp File Reference
#include <stdio.h>
*
#include <string.h>
*
#include <stdlib.h>
*
#include <errno.h>
*
#include <sys/types.h>
*
#include <sys/stat.h>
*
#include `warning.h`
*
#include `parameter.h`
*
#include `output.h`
*
Macros
#define FNAMESIZE 100
#define INITIAL_BUFSIZE 100
Functions
int OpenFileAndCheckExistance (FILE **fp, const char *fname, char *ftype)
int FileExistsP (const char *fname)
int YesNoP (const char *message)
FILE * OpenWriteFile (const char *filename)
FILE * OpenReadFile (const char *filename)
char * ReadLine (FILE *fp)
void CheckFile (FILE *fp)
char * Chext (char *filename)
Macro Definition Documentation
#define FNAMESIZE 100
Referenced by OpenWriteFile().
#define INITIAL_BUFSIZE 100
Referenced by ReadLine().
Function Documentation
void CheckFile (FILE * fp)
References errno, and error().
Referenced by ReadLine().
char* Chext (char * filename)
int FileExistsP (const char * fname)
References FALSE, and TRUE.
Referenced by OpenWriteFile().
int OpenFileAndCheckExistance (FILE ** fp, const char * fname, char * ftype)
References FALSE, and TRUE.
Referenced by OpenReadFile().
FILE* OpenReadFile (const char * filename)
References FALSE, and OpenFileAndCheckExistance().
Referenced by Parameter::Read().
FILE* OpenWriteFile (const char * filename)
References FileExistsP(), FNAMESIZE, and TRUE.
char* ReadLine (FILE * fp)
References CheckFile(), errno, error(), INITIAL_BUFSIZE, and MEMORYCHECK.
Referenced by SearchToken(), and SkipLine().
int YesNoP (const char * message)
References FALSE, and TRUE.