parse.cpp File Reference
#include <stdio.h>
*
#include <locale.h>
*
#include <string.h>
*
#include <stdlib.h>
*
#include <errno.h>
*
#include `warning.h`
*
#include `parse.h`
*
#include `output.h`
*
Functions
char * ParsePar (FILE *fp, char *parameter, bool wrapflag)
int igetpar (FILE *fp, char *parameter, bool wrapflag)
int igetpar (FILE *fp, char *parameter, int default_val, bool wrapflag)
float fgetpar (FILE *fp, char *parameter, bool wrapflag)
float fgetpar (FILE *fp, char *parameter, double default_val, bool wrapflag)
double * dgetparlist (FILE *fp, char *parameter, int n, bool wrapflag)
char * sgetpar (FILE *fp, char *parameter, bool wrapflag)
char * sgetpar (FILE *fp, char *parameter, const char *default_val, bool wrapflag)
char * bool_str (bool bool_var)
bool bgetpar (FILE *fp, char *parameter, bool wrapflag)
bool bgetpar (FILE *fp, char *parameter, int default_val, bool wrapflag)
char * SearchToken (FILE *fp, char *token, bool wrapflag)
int TokenInLineP (char *line, char *token)
void SkipLine (FILE *fp)
void SkipToken (FILE *fp, char *token, bool wrapflag)
Function Documentation
bool bgetpar (FILE * fp, char * parameter, bool wrapflag)
References bgetpar().
Referenced by bgetpar(), and Parameter::Read().
bool bgetpar (FILE * fp, char * parameter, int default_val, bool wrapflag)
References bool_str(), error(), ParsePar(), and warning().
char* bool_str (bool bool_var)
Referenced by bgetpar().
double* dgetparlist (FILE * fp, char * parameter, int n, bool wrapflag)
References error(), ParsePar(), and warning().
Referenced by Parameter::Read().
float fgetpar (FILE * fp, char * parameter, bool wrapflag)
References fgetpar().
Referenced by fgetpar(), and Parameter::Read().
float fgetpar (FILE * fp, char * parameter, double default_val, bool wrapflag)
References ParsePar(), and warning().
int igetpar (FILE * fp, char * parameter, bool wrapflag)
References igetpar().
Referenced by igetpar(), and Parameter::Read().
int igetpar (FILE * fp, char * parameter, int default_val, bool wrapflag)
References ParsePar(), and warning().
char* ParsePar (FILE * fp, char * parameter, bool wrapflag)
References error(), SearchToken(), and warning().
Referenced by bgetpar(), dgetparlist(), fgetpar(), igetpar(), and sgetpar().
char* SearchToken (FILE * fp, char * token, bool wrapflag)
References errno, error(), ReadLine(), and warning().
Referenced by ParsePar(), and SkipToken().
char* sgetpar (FILE * fp, char * parameter, bool wrapflag)
References sgetpar().
Referenced by Parameter::Read(), and sgetpar().
char* sgetpar (FILE * fp, char * parameter, const char * default_val, bool wrapflag)
References ParsePar(), and warning().
void SkipLine (FILE * fp)
References ReadLine().
void SkipToken (FILE * fp, char * token, bool wrapflag)
References error(), and SearchToken().
int TokenInLineP (char * line, char * token)