random.cpp File Reference
#include <stdio.h>
*
#include <stdlib.h>
*
#include <sys/timeb.h>
*
#include <iostream>
*
#include `random.h`
*
Functions
double RANDOM (void)
int Seed (int seed)
long RandomNumber (long max)
void AskSeed (void)
int Randomize (void)
Function Documentation
void AskSeed (void)
Interactively ask for the seed
Parameters
void
Returns
void
References Seed().
double RANDOM (void)
Returns
A random double between 0 and 1
References FAC, MBIG, MSEED, and MZ.
Referenced by CellularPotts::AmoebaeMove(), CellularPotts::GrowInCells(), RandomNumber(), and Seed().
int Randomize (void)
Make a random seed based on the local time
Parameters
void
Returns
void
References Seed().
Referenced by Seed().
long RandomNumber (long max)
Returns a random integer value between 1 and 'max'
Parameters
The maximum value (long)
Returns
A random integer (long)
References RANDOM().
Referenced by CellularPotts::GrowInCells(), CellularPotts::SetRandomTypes(), and CellularPotts::ThrowInCells().
int Seed (int seed)
Parameters
An integer random seed
Returns
the random seed
References RANDOM(), and Randomize().
Referenced by AskSeed(), and Randomize().