sticky.h File Reference
Macros
#define GRIDX 100
#define GRIDY 100
#define MAXCELLS 1024 /* beware */
#define MAXNEIGH 2054
#define FALSE 0
#define TRUE 1
#define OK 1
#define TESTCELLS 1
#define BOLTZMANN 1024
#define MAXSEED 65531349
#define MAXHIST 4096
#define MAXTYPE 256
#define WHITE 0
#define BLACK 1
#define RED 2
#define BLUE 3
#define GREEN 4
#define MEDIUM 0
#define EMPTY -1
#define DIV 1 /* DIV 2^(# of divbit) */
#define REMARK 56
#define HASHCOLPRIME 255
#define PLOTPERIODFREQUENCY 25
#define HOSTDEAD -20
#define NULL_BEAST -10
#define OK_BEAST -5
#define PMUT 0.009
#define PMUT2 .1
#define DMUT 0.0021
#define PCO 0.
#define NETSIZE 29
#define INETSIZE 16
#define INP_PROT 16 /* number of negative inputs (connectivity) */
#define POTPROT 16 /* number of potential proteins */
#define COMMUNICATION 2
#define ENERGYOFFSET 8
#define NHHIST 10
#define NH_TH 0.5
#define ENDOFSTATES 1<<(NETSIZE+2)
Functions
double RANDOM ()
Macro Definition Documentation
#define BLACK 1
#define BLUE 3
#define BOLTZMANN 1024
#define COMMUNICATION 2
#define DIV 1 /* DIV 2^(# of divbit) */
#define DMUT 0.0021
#define EMPTY -1
Referenced by Cell::ClearJ(), and CellularPotts::SearchNandPlot().
#define ENDOFSTATES 1<<(NETSIZE+2)
#define ENERGYOFFSET 8
#define FALSE 0
#define GREEN 4
#define GRIDX 100
#define GRIDY 100
#define HASHCOLPRIME 255
#define HOSTDEAD -20
#define INETSIZE 16
#define INP_PROT 16 /* number of negative inputs (connectivity) */
#define MAXCELLS 1024 /* beware */
#define MAXHIST 4096
#define MAXNEIGH 2054
#define MAXSEED 65531349
#define MAXTYPE 256
#define MEDIUM 0
#define NETSIZE 29
#define NH_TH 0.5
#define NHHIST 10
#define NULL_BEAST -10
#define OK 1
#define OK_BEAST -5
#define PCO 0.
#define PLOTPERIODFREQUENCY 25
#define PMUT 0.009
#define PMUT2 .1
#define POTPROT 16 /* number of potential proteins */
#define RED 2
#define REMARK 56
#define TESTCELLS 1
#define TRUE 1
#define WHITE 0
Function Documentation
double RANDOM (void)
Returns
A random double between 0 and 1
References FAC, MBIG, MSEED, and MZ.
Referenced by CellularPotts::AmoebaeMove(), CellularPotts::GrowInCells(), RandomNumber(), and Seed().