warning.h File Reference
Macros
#define MEMORYCHECK(x) if ((x)==NULL) { fprintf(stderr, `Out of Memory error in `#x` \n`); exit(0); }
#define UNIDENTIFIED 2353996
Functions
void error (char *,...)
void warning (char *,...)
Macro Definition Documentation
#define MEMORYCHECK(x) if ((x)==NULL) { fprintf(stderr, `Out of Memory error in `#x` \n`); exit(0); }
Referenced by ReadLine().
#define UNIDENTIFIED 2353996
Function Documentation
void error (char * , ...)
Referenced by bgetpar(), CheckFile(), dgetparlist(), ParsePar(), ReadLine(), SearchToken(), and SkipToken().
void warning (char * , ...)
References Quiet.
Referenced by bgetpar(), dgetparlist(), fgetpar(), igetpar(), ParsePar(), SearchToken(), and sgetpar().