warning.cpp File Reference
#include <stdarg.h>
*
#include <stdio.h>
*
#include <stdlib.h>
*
#include `warning.h`
*
Functions
void error (char *fmt,...)
void warning (char *fmt,...)
Variables
int Quiet =0
Function Documentation
void error (char * fmt, ...)
Referenced by bgetpar(), CheckFile(), dgetparlist(), ParsePar(), ReadLine(), SearchToken(), and SkipToken().
void warning (char * fmt, ...)
References Quiet.
Referenced by bgetpar(), dgetparlist(), fgetpar(), igetpar(), ParsePar(), SearchToken(), and sgetpar().
Variable Documentation
int Quiet =0
Referenced by warning().