// Copyright (c) 2005-2016 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD/e, an XML Schema
// to C++ data binding compiler for embedded systems.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
//
// End prologue.

namespace phenotype
{
  // phenotype_elements_sskel
  //

  inline
  void phenotype_elements_sskel::
  adhesion_serializer (::phenotype_common::adhesion_sskel& s)
  {
    this->adhesion_serializer_ = &s;
  }

  inline
  void phenotype_elements_sskel::
  adhesion_serializer (::xml_schema::serializer_map& m)
  {
    this->adhesion_serializer_map_ = &m;
  }

  inline
  void phenotype_elements_sskel::
  geometrical_properties_serializer (::phenotype_common::geometrical_properties_sskel& s)
  {
    this->geometrical_properties_serializer_ = &s;
  }

  inline
  void phenotype_elements_sskel::
  geometrical_properties_serializer (::xml_schema::serializer_map& m)
  {
    this->geometrical_properties_serializer_map_ = &m;
  }

  inline
  void phenotype_elements_sskel::
  mass_serializer (::phenotype_common::mass_sskel& s)
  {
    this->mass_serializer_ = &s;
  }

  inline
  void phenotype_elements_sskel::
  mass_serializer (::xml_schema::serializer_map& m)
  {
    this->mass_serializer_map_ = &m;
  }

  inline
  void phenotype_elements_sskel::
  mechanics_serializer (::phenotype_common::mechanics_sskel& s)
  {
    this->mechanics_serializer_ = &s;
  }

  inline
  void phenotype_elements_sskel::
  mechanics_serializer (::xml_schema::serializer_map& m)
  {
    this->mechanics_serializer_map_ = &m;
  }

  inline
  void phenotype_elements_sskel::
  motility_serializer (::phenotype_common::motility_sskel& s)
  {
    this->motility_serializer_ = &s;
  }

  inline
  void phenotype_elements_sskel::
  motility_serializer (::xml_schema::serializer_map& m)
  {
    this->motility_serializer_map_ = &m;
  }

  inline
  void phenotype_elements_sskel::
  PKPD_serializer (::pkpd::PKPD_sskel& s)
  {
    this->PKPD_serializer_ = &s;
  }

  inline
  void phenotype_elements_sskel::
  PKPD_serializer (::xml_schema::serializer_map& m)
  {
    this->PKPD_serializer_map_ = &m;
  }

  inline
  void phenotype_elements_sskel::
  timescale_serializer (::phenotype_base::expected_timescale_sskel& s)
  {
    this->timescale_serializer_ = &s;
  }

  inline
  void phenotype_elements_sskel::
  timescale_serializer (::xml_schema::serializer_map& m)
  {
    this->timescale_serializer_map_ = &m;
  }

  inline
  void phenotype_elements_sskel::
  transport_processes_serializer (::phenotype_common::transport_processes_sskel& s)
  {
    this->transport_processes_serializer_ = &s;
  }

  inline
  void phenotype_elements_sskel::
  transport_processes_serializer (::xml_schema::serializer_map& m)
  {
    this->transport_processes_serializer_map_ = &m;
  }

  inline
  void phenotype_elements_sskel::
  custom_serializer (::common::custom_sskel& s)
  {
    this->custom_serializer_ = &s;
  }

  inline
  void phenotype_elements_sskel::
  custom_serializer (::xml_schema::serializer_map& m)
  {
    this->custom_serializer_map_ = &m;
  }

  inline
  void phenotype_elements_sskel::
  serializers (::cell_cycle::cell_cycle_sskel& cell_cycle,
               ::cell_cycle::cell_death_sskel& cell_death,
               ::phenotype_common::adhesion_sskel& adhesion,
               ::phenotype_common::geometrical_properties_sskel& geometrical_properties,
               ::phenotype_common::mass_sskel& mass,
               ::phenotype_common::mechanics_sskel& mechanics,
               ::phenotype_common::motility_sskel& motility,
               ::pkpd::PKPD_sskel& PKPD,
               ::phenotype_base::expected_timescale_sskel& timescale,
               ::phenotype_common::transport_processes_sskel& transport_processes,
               ::common::custom_sskel& custom)
  {
    this->cell_cycle_serializer_ = &cell_cycle;
    this->cell_death_serializer_ = &cell_death;
    this->adhesion_serializer_ = &adhesion;
    this->geometrical_properties_serializer_ = &geometrical_properties;
    this->mass_serializer_ = &mass;
    this->mechanics_serializer_ = &mechanics;
    this->motility_serializer_ = &motility;
    this->PKPD_serializer_ = &PKPD;
    this->timescale_serializer_ = &timescale;
    this->transport_processes_serializer_ = &transport_processes;
    this->custom_serializer_ = &custom;
  }

  inline
  void phenotype_elements_sskel::
  serializer_maps (::xml_schema::serializer_map& cell_cycle,
                   ::xml_schema::serializer_map& cell_death,
                   ::xml_schema::serializer_map& adhesion,
                   ::xml_schema::serializer_map& geometrical_properties,
                   ::xml_schema::serializer_map& mass,
                   ::xml_schema::serializer_map& mechanics,
                   ::xml_schema::serializer_map& motility,
                   ::xml_schema::serializer_map& PKPD,
                   ::xml_schema::serializer_map& timescale,
                   ::xml_schema::serializer_map& transport_processes,
                   ::xml_schema::serializer_map& custom)
  {
    this->cell_cycle_serializer_map_ = &cell_cycle;
    this->cell_death_serializer_map_ = &cell_death;
    this->adhesion_serializer_map_ = &adhesion;
    this->geometrical_properties_serializer_map_ = &geometrical_properties;
    this->mass_serializer_map_ = &mass;
    this->mechanics_serializer_map_ = &mechanics;
    this->motility_serializer_map_ = &motility;
    this->PKPD_serializer_map_ = &PKPD;
    this->timescale_serializer_map_ = &timescale;
    this->transport_processes_serializer_map_ = &transport_processes;
    this->custom_serializer_map_ = &custom;
  }

  inline
  phenotype_elements_sskel::
  phenotype_elements_sskel (::cell_cycle::cycles_and_deaths_sskel* tiein)
  : ::cell_cycle::cycles_and_deaths_sskel (tiein, 0),
    phenotype_elements_impl_ (0),
    adhesion_serializer_ (0),
    adhesion_serializer_map_ (0),
    geometrical_properties_serializer_ (0),
    geometrical_properties_serializer_map_ (0),
    mass_serializer_ (0),
    mass_serializer_map_ (0),
    mechanics_serializer_ (0),
    mechanics_serializer_map_ (0),
    motility_serializer_ (0),
    motility_serializer_map_ (0),
    PKPD_serializer_ (0),
    PKPD_serializer_map_ (0),
    timescale_serializer_ (0),
    timescale_serializer_map_ (0),
    transport_processes_serializer_ (0),
    transport_processes_serializer_map_ (0),
    custom_serializer_ (0),
    custom_serializer_map_ (0)
  {
  }

  inline
  phenotype_elements_sskel::
  phenotype_elements_sskel (phenotype_elements_sskel* impl, void*)
  : ::cell_cycle::cycles_and_deaths_sskel (impl, 0),
    phenotype_elements_impl_ (impl),
    adhesion_serializer_ (0),
    adhesion_serializer_map_ (0),
    geometrical_properties_serializer_ (0),
    geometrical_properties_serializer_map_ (0),
    mass_serializer_ (0),
    mass_serializer_map_ (0),
    mechanics_serializer_ (0),
    mechanics_serializer_map_ (0),
    motility_serializer_ (0),
    motility_serializer_map_ (0),
    PKPD_serializer_ (0),
    PKPD_serializer_map_ (0),
    timescale_serializer_ (0),
    timescale_serializer_map_ (0),
    transport_processes_serializer_ (0),
    transport_processes_serializer_map_ (0),
    custom_serializer_ (0),
    custom_serializer_map_ (0)
  {
  }

  // phenotype_sskel
  //

  inline
  void phenotype_sskel::
  type_serializer (::phenotype_base::phenotype_type_sskel& type)
  {
    this->type_serializer_ = &type;
  }

  inline
  void phenotype_sskel::
  serializers (::cell_cycle::cell_cycle_sskel& cell_cycle,
               ::cell_cycle::cell_death_sskel& cell_death,
               ::phenotype_common::adhesion_sskel& adhesion,
               ::phenotype_common::geometrical_properties_sskel& geometrical_properties,
               ::phenotype_common::mass_sskel& mass,
               ::phenotype_common::mechanics_sskel& mechanics,
               ::phenotype_common::motility_sskel& motility,
               ::pkpd::PKPD_sskel& PKPD,
               ::phenotype_base::expected_timescale_sskel& timescale,
               ::phenotype_common::transport_processes_sskel& transport_processes,
               ::common::custom_sskel& custom,
               ::phenotype_base::phenotype_type_sskel& type)
  {
    this->cell_cycle_serializer_ = &cell_cycle;
    this->cell_death_serializer_ = &cell_death;
    this->adhesion_serializer_ = &adhesion;
    this->geometrical_properties_serializer_ = &geometrical_properties;
    this->mass_serializer_ = &mass;
    this->mechanics_serializer_ = &mechanics;
    this->motility_serializer_ = &motility;
    this->PKPD_serializer_ = &PKPD;
    this->timescale_serializer_ = &timescale;
    this->transport_processes_serializer_ = &transport_processes;
    this->custom_serializer_ = &custom;
    this->type_serializer_ = &type;
  }

  inline
  phenotype_sskel::
  phenotype_sskel (::phenotype::phenotype_elements_sskel* tiein)
  : ::phenotype::phenotype_elements_sskel (tiein, 0),
    phenotype_impl_ (0),
    type_serializer_ (0)
  {
  }

  inline
  phenotype_sskel::
  phenotype_sskel (phenotype_sskel* impl, void*)
  : ::phenotype::phenotype_elements_sskel (impl, 0),
    phenotype_impl_ (impl),
    type_serializer_ (0)
  {
  }
}

// Begin epilogue.
//
//
// End epilogue.

